/* Gilles tools around the flex scanner to allow for easier interaction
 * outside a yacc/bison environment. */

#ifndef SIMPLE_ASSIGN_TOKENS_H
#define SIMPLE_ASSIGN_TOKENS_H

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     INT = 301,
     FLOAT = 300,
     PLUS = 260,
     MINUS = 259,
     MULT = 262,
     DIV = 261,
     EXPON = 263,
     SEMICOLON = 264,
     OPAR = 265,
     FPAR = 266,
     VAR = 267,
     MODULO = 268,
     ASSIGN = 269,
     UNDERSCORE = 270,
     OCROCH = 271,
     FCROCH = 272,
     COMBINATION = 273,
     SINE = 274,
     COSINE = 275,
     PI = 276
   };
#endif
/* Tokens.  */
#define INT 301
#define FLOAT 300
#define PLUS 260
#define MINUS 259
#define MULT 262
#define DIV 261
#define EXPON 263
#define SEMICOLON 264
#define OPAR 265
#define FPAR 266
#define VAR 267
#define MODULO 268
#define ASSIGN 269
#define UNDERSCORE 270
#define OCROCH 271
#define FCROCH 272
#define COMBINATION 273
#define SINE 274
#define COSINE 275
#define PI 276





typedef struct Token {
    int type;
    char * text;
    float value; // only defined when the token type allows for it
    int intValue; // only defined when the token type allows for it
} Token;

/*Token * _newToken(int type, int compute_float_value);*/

void _freeToken(Token* t);

// Define the profile of the yylex function generated by flex tool.
#define YY_DECL Token *yylex(void)

#endif //SIMPLE_ASSIGN_TOKENS_H
